### PR TITLE
gcdeck: Re-scale slides when window is resized.

### PR DESCRIPTION
**Pull request by andybalholm**
The slides will resize to fill the new window size.

### CODE REVIEW

**Comment by gedw99** [comment]
wondering if we shoudl expose it as an option on the args here: https://github.com/ajstarks/giocanvas/tree/master/gcdeck#options 

then you can express resize there.. 

some people might want fixed size still.

**Comment by andybalholm** [comment]
There are probably more people who would want an option to keep the proportions, than who would want it to stay exactly the same size when the window is resized.

**Comment by gedw99** [comment]
well, my use case is to have both resize and / or fixed.  

so then from:
```sh
-pagesize string
    	pagesize: w,h, or one of: Letter, Legal, Tabloid, A3, A4, A5, ArchA, 4R, Index, Widescreen (default "Letter")
``´ 

```sh
-pagesize string
    	pagesize: w,h, or one of: Letter, Legal, Tabloid, A3, A4, A5, ArchA, 4R, Index, Widescreen (default "Letter"), resizable 
```

**Comment by andybalholm** [comment]
That sounds like a good way to do it. But how would it pick the initial window size?

**Comment by gedw99** [comment]
https://github.com/ajstarks/giocanvas/blob/48a62d59de5358c49d90c067f7be757e5037a456/gcdeck/gcdeck.go#L617

```sh
deck, err := readDeck(filename, width, height)
```

We need to feedback that current / session GIOUI window size back into that call so readDeck can recreate the xml that holds the absolute positions.

**Comment by andybalholm** [comment]
The code I have works without that. Maybe that would give more accurate positions, though. But we don't want to need to re-read the XML file on every frame…

**Comment by gedw99** [comment]
I need to run the code then to see what your mean about positions.

I am going to raise another issue related to this - you jogged my memory..

**Comment by ajstarks** [comment]
See revision https://github.com/ajstarks/giocanvas/commit/b22c8db862c53b58bec44fbc3cd9383994a048cc

if you do not resize, the specified (or default) pagesize is used. If you resize the window, the deck is proportionally resized. No other command line option is required.

**Pull request closed without merging**
